from ptpma import PMALed, PMAButton, PMABuzzer, PMAUltrasonicSensor, PMALightSensor, PMASoundSensor,  PMAPotentiometer
from time import sleep

gled = PMALed("D2")
yled = PMALed("D1")
rled = PMALed("D0")
button = PMAButton("D3")
buzz = PMABuzzer("D4")
us = PMAUltrasonicSensor("D5")
testrn = PMAButton("D6")
ls = PMALightSensor("A0")
ss = PMASoundSensor("A1")
select = PMAPotentiometer("A2")

def read():
    print("Reading in 3 sec. Move sensors to desired spot/place now.")
    sleep(3)
    print(us.distance)
    sleep(0.1)
    print(ls.reading)
    sleep(0.1)
    print(ss.reading)
    sleep(0.2)
def readfortest():
    sleep(0.1)
    print(us.distance)
    sleep(0.1)
    print(ls.reading)
    sleep(0.1)
    print(ss.reading)
    sleep(0.2)
def test():
    gled.on()
    yled.on()
    rled.on()
    buzz.on()
    print("Reading in 5 sec. Move sensors to desired LED/buzzer now.")
    sleep(5)
    readfortest()
    gled.off()
    yled.off()
    rled.off()
    buzz.off()
print("")
print("Reading Guide:")
print("-----------------")
print("Ultrasonic Sensor")
print("Light Sensor")
print("Sound Sensor")

while True:
    gled.on()
    if button.is_pressed:
        print("Traffic Lights Starting...")
        sleep(1.5)
        gled.off()
        sleep(0.1)
        yled.on()
        sleep(3)
        yled.off()
        sleep(0.1)
        rled.on()
        sleep(0.1)
        buzz.on()
        sleep(6)
        buzz.off()
        sleep(0.1)
        rled.off()
        sleep(0.1)
        print("Traffic Lights Done")
    if testrn.is_pressed:
        if select.position <500:
            read()
        else:
            test()