from ptpma import PMALed, PMAButton, PMABuzzer, PMAUltrasonicSensor, PMALightSensor, PMASoundSensor,  PMAPotentiometer
from time import sleep
gled = PMALed("D2")
yled = PMALed("D1")
rled = PMALed("D0")
button = PMAButton("D3")
buzz = PMABuzzer("D4")
us = PMAUltrasonicSensor("D5")
testrn = PMAButton("D6")
ls = PMALightSensor("A0")
ss = PMASoundSensor("A1")
select = PMAPotentiometer("A2")
def party():
    #print("Party Time!")
    for i in range(10):
        gled.on()
        buzz.on()
        sleep(0.5)
        gled.off()
        yled.on()
        sleep(0.5)
        buzz.off()
        yled.off()
        rled.on()
        sleep(0.5)
        buzz.on()
        rled.off()
        sleep(0.3)
        buzz.off()
        sleep(0.1)
    gled.on()
    yled.on()
    rled.on()
    buzz.on()
    sleep(3)
    buzz.off()
    rled.off()
    yled.off()
    gled.off()
    #print("And the party is done!")
print("Party time!)
while True:
    party()